services:
  web:
    image: "nginx"
    ports: 
      - "8080:80"
    networks: 
      - my_network
    depends_on:
      # - db
      - rcache
  rcache:
    image: "erick2113/radis"
    # ports:
    #   - "6379:6379"
    networks: 
      - my_network
    

  db:
    image: "mysql"
    profiles: 
    # if  profiles set it define it not run that particular image by default you should run it explicitly
    # 'docker compose --profile enabledb up -d' -> using this command you can run it 
        - enabledb
networks:
  my_network:
    driver: bridge # if network is bridge then the container whoever use this network can communicate with each other
    
